<a href="https://colab.research.google.com/github/Vishal35198/Linear_Reg-From-Scratch/blob/main/DPL_Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Importing the Packages
import torch
import numpy as np

In [4]:
x = torch.tensor(3.,requires_grad=True)
w = torch.tensor(4.,requires_grad= True)
b = torch.tensor(5.,requires_grad=True)

In [5]:
y = x*w +b

In [6]:
y

tensor(17., grad_fn=<AddBackward0>)

In [7]:
y.backward()
y

tensor(17., grad_fn=<AddBackward0>)

In [8]:
print(f'The derivative of y wrt to b is {w.grad}')

The derivative of y wrt to b is 3.0


In [9]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [10]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [11]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
type(inputs)

torch.Tensor

# Linear Regression From Scratch

In [12]:
w = torch.rand(2,3,requires_grad=True)
b = torch.rand(2,requires_grad=True)

In [13]:
def model(x):
  return x @ w.t() + b

In [14]:
preds = model(inputs)
preds

tensor([[ 84.2973,  63.2717],
        [111.8393,  85.3703],
        [138.2148,  99.3956],
        [ 75.8752,  57.3237],
        [112.1300,  86.6366]], grad_fn=<AddBackward0>)

In [15]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Loss Function

In [16]:
def loss(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [17]:
loss(targets,preds)

tensor(798.6157, grad_fn=<DivBackward0>)

In [18]:
tu = (10)
tu

10

In [19]:
list1 = [10,20,30]
list1.insert(7,30)
list1

[10, 20, 30, 30]

In [20]:
def sample_value(value):
  sum1 = 0
  for i in value:
    if i%2 !=0:
      sum1+= value[i]
    else:
      sum1-=i

  print(sum1)


In [21]:
dict1 = {1:2,2:4,3:6,5:8}
sample_value(dict1)

14


# Using Pytorch inbuilts

In [22]:
import torch.nn as nn

In [30]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs.shape)

torch.Size([15, 3])


# dataset and dataloader

In [24]:
from torch.utils.data import TensorDataset

In [25]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

# Dataloader

In [27]:
from torch.utils.data import DataLoader

In [28]:
# using the dataloader class for train_ds, batch_size
train_dl = DataLoader(train_ds,batch_size=5,shuffle = True)

In [29]:
len(train_dl)

3

# Using a linear model from nn.linear

In [35]:
model = nn.Linear(3,2)
# defining a linear model for 3 inputs and 2 output so 3,2
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4730, -0.3226,  0.4859],
        [-0.5472, -0.2069, -0.0740]], requires_grad=True)
Parameter containing:
tensor([-0.2933, -0.5253], requires_grad=True)


#### Generating a preds from the linear model with random weights and bias

In [36]:
preds = model(inputs)
preds

tensor([[ 33.5142, -57.5188],
        [ 45.4571, -73.2689],
        [ 25.8097, -80.1553],
        [ 52.0585, -67.9761],
        [ 35.3855, -63.3307],
        [ 34.3098, -57.8590],
        [ 46.2656, -73.1360],
        [ 26.7686, -80.7765],
        [ 51.2629, -67.6358],
        [ 35.3984, -62.8576],
        [ 34.3227, -57.3859],
        [ 46.2527, -73.6091],
        [ 25.0012, -80.2881],
        [ 52.0457, -68.4492],
        [ 34.5899, -62.9905]], grad_fn=<AddmmBackward0>)

In [37]:
import torch.nn.functional as F

In [39]:
loss_fn = F.mse_loss

In [41]:
loss = loss_fn(preds,targets)
print(loss)

tensor(15220.8955, grad_fn=<MseLossBackward0>)


# Since the loss is Heavy we will optimize using backpropogation

In [43]:
opt = torch.optim.SGD(model.parameters(),lr=1e-5)
print(opt)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 1e-05
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


# TrainModel

In [44]:
# function to train the model
def fit(epochs,model,loss_fn,opt,train_dl):
  for epoch in range(epochs):
    # training in batches
    for x_b,y_b in train_dl:
      pred = model(x_b)
      loss = loss_fn(pred,y_b)
      # computer the gradient
      loss.backward()
      opt.step()
      opt.zero_grad()

    if (epoch+1)%10 ==0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, loss.item()))


In [48]:
fit(500,model,loss_fn,opt,train_dl)

Epoch [10/500], Loss: 1.3226
Epoch [20/500], Loss: 1.4889
Epoch [30/500], Loss: 1.9007
Epoch [40/500], Loss: 0.7260
Epoch [50/500], Loss: 0.8648
Epoch [60/500], Loss: 1.1557
Epoch [70/500], Loss: 1.4598
Epoch [80/500], Loss: 1.5711
Epoch [90/500], Loss: 1.7319
Epoch [100/500], Loss: 1.3845
Epoch [110/500], Loss: 0.9012
Epoch [120/500], Loss: 1.3646
Epoch [130/500], Loss: 0.8693
Epoch [140/500], Loss: 1.4601
Epoch [150/500], Loss: 1.1007
Epoch [160/500], Loss: 1.1769
Epoch [170/500], Loss: 0.7485
Epoch [180/500], Loss: 1.6870
Epoch [190/500], Loss: 1.6350
Epoch [200/500], Loss: 1.3457
Epoch [210/500], Loss: 1.2366
Epoch [220/500], Loss: 1.0206
Epoch [230/500], Loss: 1.0484
Epoch [240/500], Loss: 1.3692
Epoch [250/500], Loss: 1.6238
Epoch [260/500], Loss: 1.3529
Epoch [270/500], Loss: 1.3332
Epoch [280/500], Loss: 1.5671
Epoch [290/500], Loss: 1.3587
Epoch [300/500], Loss: 1.1437
Epoch [310/500], Loss: 1.3240
Epoch [320/500], Loss: 0.8450
Epoch [330/500], Loss: 0.7402
Epoch [340/500], Lo

In [51]:
preds = model(inputs)
print(preds)

tensor([[ 56.8994,  70.3205],
        [ 82.0799, 100.4789],
        [118.1690, 133.0421],
        [ 20.8161,  37.8293],
        [101.8852, 118.2518],
        [ 55.6555,  69.2440],
        [ 81.9417, 100.5577],
        [118.4694, 133.6404],
        [ 22.0599,  38.9058],
        [102.9908, 119.4071],
        [ 56.7611,  70.3993],
        [ 80.8361,  99.4023],
        [118.3073, 132.9633],
        [ 19.7105,  36.6739],
        [103.1291, 119.3284]], grad_fn=<AddmmBackward0>)


In [52]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])